services:
  valkey:
    image: valkey/valkey
  
  robotic-arm-aas:
    build: .
    ports:
      - 8000:8000
    environment:
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
    depends_on:
      - valkey
